apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpouse: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpouse: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpouse: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
